### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [TianyiChen/POJ-exercises#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by TianyiChen** [comment]
Hello,
The aim of this repo is to inspire others that maybe they can write a better solution after reading mine.
And currently I do not want to give up any rights.
So this repo's copyright status is: All rights reserved.
I've indicated this point in the README file, and a LICENSE file which has similar meaning has been added in response to this issue.
Thanks for your suggestion.

**Comment by karan** [comment]
Thanks for being conscious @TianyiChen
